// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyInventory2026.src.shared.context;

#nullable disable

namespace MyInventory2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410113948_productMigration")]
    partial class productMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyInventory2026.src.modules.products.Infrastructure.Entity.ProductEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("codeInv")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code_inv");

                    b.Property<string>("nameProduct")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_product");

                    b.Property<int>("stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("stockMax")
                        .HasColumnType("int")
                        .HasColumnName("stock_max");

                    b.Property<int>("stockMin")
                        .HasColumnType("int")
                        .HasColumnName("stock_min");

                    b.HasKey("id");

                    b.HasIndex("codeInv")
                        .IsUnique()
                        .HasDatabaseName("IX_products_codeInv");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_stock", "stock > 0");

                            t.HasCheckConstraint("CK_products_stock_max", "stock_max > stock_min");

                            t.HasCheckConstraint("CK_products_stock_min", "stock_min > 0");
                        });
                });

            modelBuilder.Entity("MyInventory2026.src.modules.provider.Infrastructure.entity.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("ProductEntityProviderEntity", b =>
                {
                    b.Property<int>("Productsid")
                        .HasColumnType("int");

                    b.Property<string>("ProvidersId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Productsid", "ProvidersId");

                    b.HasIndex("ProvidersId");

                    b.ToTable("ProductProviders", (string)null);
                });

            modelBuilder.Entity("ProductEntityProviderEntity", b =>
                {
                    b.HasOne("MyInventory2026.src.modules.products.Infrastructure.Entity.ProductEntity", null)
                        .WithMany()
                        .HasForeignKey("Productsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyInventory2026.src.modules.provider.Infrastructure.entity.ProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
